[package]
name = "macro_derive_list"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[[test]]
name="entry"
path="tests/entry.rs"

[dependencies]
quote = "1.0.42"
syn = "2.0.111"
trybuild = "1.0.114"
